version: "3.9"
services:
  postgres:
    image: postgres:15.5
    container_name: db
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - backend-pg-data:/var/lib/postgresql/data

  backend:
    image: backend:0.0.1
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/db
volumes:
  backend-pg-data: