spring:
  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  messages:
    basename: i18n/messages

  #liquibase
  liquibase.change-log: classpath:/db/changelog/db-changelog.xml

  kafka:
    enable: true

    topic-name:
      images-wip: images.wip
      images-done: images.done

    producer:
      properties:
        spring:
          json:
            add.type.headers: false

    consumer:
      properties:
        spring.json.trusted.packages: "*"
    admin:
      properties:
        min-in-sync-replicas: 2
    listener.ack-mode: manual
    bootstrap-servers:
      - localhost:9092
      - localhost:9093
      - localhost:9094

  cloud:
    zookeeper:
      config.enabled: false
      connect-string: localhost:2181

minio:
  ttl-days: 3

bucket4j:
  enabled: true
  cache-to-use: custom
  methods:
    - name: imagga-get-tags-limit
      cache-name: imagga-get-tags-limit
      rate-limit:
        num-tokens: 1
        post-execute-condition: true # token consumes only after method executed (method throw ex - not consume)
        bandwidths:
          - capacity: 1000
            time: 30
            unit: Days
            refill-speed: interval