version: "3.9"
services:
  postgres:
    image: postgres:15.5
    container_name: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio:RELEASE.2024-03-30T09-41-56Z
    container_name: minio
    command: server /data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    volumes:
      - minio-data:/data

  backend:
    image: backend:0.0.1
    build:
      context: ../..
      dockerfile: ../Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - minio
    environment:
      - APP_SECURITY_JWT_SECRET_KEY=55e4c0251ac3f4a8497d719e4e81e13d8ae58a6e8878aac7f62a65fe92d66ba6
      - APP_SECURITY_JWT_REFRESH_TOKEN_EXPIRATION_MIN=4320
      - APP_SECURITY_JWT_ACCESS_TOKEN_EXPIRATION_MIN=5
      - APP_SECURITY_JWT_COOKIE_HTTPS_ONLY=false
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
      - MINIO_DATASOURCE_USERNAME=minioadmin
      - MINIO_DATASOURCE_PASSWORD=minioadmin
      - MINIO_DATASOURCE_URL=http://minio:9000
      - MINIO_BUCKET_NAME=data
      - SCHEDULER_ENABLED=true
      - SCHEDULER_DELETEEXPIREDTOKENSCRON=0 0 * * * ?
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect

volumes:
  pg-data:
  minio-data: