spring:
  datasource:
    driver-class-name: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  messages:
    basename: i18n/messages

  #liquibase
  liquibase.change-log: classpath:/db/changelog/db-changelog.xml

  kafka:
    enable: true

    producer:
      properties:
        spring:
          json:
            add.type.headers: false

    consumer:
      properties:
        spring.json.trusted.packages: "*"
    admin:
      properties:
        min-in-sync-replicas: 2
    listener.ack-mode: manual
    bootstrap-servers:
      - localhost:9092
      - localhost:9093
      - localhost:9094

  cloud:
    zookeeper:
      config.enabled: false
      connect-string: localhost:2181

app:
  group-id: ${GROUP_ID:api-group-id}

bucket4j:
  enabled: true
  cache-to-use: custom # disable auto config
  methods:
    - name: apply-filters-limit
      cache-name: apply-filters-limit
      rate-limit:
        num-tokens: 1
        bandwidths: # maximum of 3 requests within 10 seconds
          - capacity: 3
            time: 10
            unit: seconds